# Standard Alembic migration script template.
# Generated by `alembic revision` / `alembic revision --autogenerate`.

"""add admin user login history

Revision ID: 5463e25973f9
Revises: h4i5j6k7l8m9
Create Date: 2026-08-26 21:04:35.465430

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5463e25973f9'
down_revision: Union[str, None] = 'h4i5j6k7l8m9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.create_table('admin_user_login',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('logged_in_at', sa.DateTime(), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['admin_user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_admin_user_login_user_id'), 'admin_user_login', ['user_id'], unique=False)


def downgrade() -> None:
    op.drop_index(op.f('ix_admin_user_login_user_id'), table_name='admin_user_login')
    op.drop_table('admin_user_login')
