# Standard Alembic migration script template.
# Generated by `alembic revision` / `alembic revision --autogenerate`.

"""widen design background_color to fit @default:<uuid> references

Revision ID: 6a7b8c9d0e1f
Revises: 5463e25973f9
Create Date: 2026-09-12

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6a7b8c9d0e1f'
down_revision: Union[str, None] = '5463e25973f9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    with op.batch_alter_table('design') as batch_op:
        batch_op.alter_column('background_color', existing_type=sa.String(length=20),
                               type_=sa.String(length=64), existing_nullable=True)


def downgrade() -> None:
    with op.batch_alter_table('design') as batch_op:
        batch_op.alter_column('background_color', existing_type=sa.String(length=64),
                               type_=sa.String(length=20), existing_nullable=True)
