import type { TourDefinition } from '../types'

// If the person clicked "Next" instead of Cancel/Adopt, the Adopt Device
// dialog is still open — but the table underneath (the next step's target)
// is already mounted regardless of the dialog, so waitForElement would
// find it immediately and highlight it *behind* the still-open dialog
// instead of skipping. Clicking Cancel here closes it exactly like a real
// dismissal would. No-op if the dialog's already closed.
const closeAdoptDialogIfStillOpen = () => {
  document.querySelector<HTMLElement>('[data-tour="devices-adopt-cancel"]')?.click()
}

// Same reasoning, for the Assign to Screen dialog opened by the
// "Assign to Screen" step's advanceOnClick.
const closeAssignDialogIfStillOpen = () => {
  document.querySelector<HTMLElement>('[data-tour="devices-assign-cancel"]')?.click()
}

export const devicesTour: TourDefinition = {
  id: 'devices',
  title: 'Devices & Matrix',
  description: 'Pair physical hardware to a screen, then bulk-assign screens to groups.',
  icon: 'pi pi-desktop',
  category: 'admin',
  steps: [
    {
      route: '/devices',
      selector: '[data-tour="devices-page"]',
      title: 'Devices',
      description:
        'A device is a piece of physical (or virtual) hardware running the screen client — it only shows anything once paired to a Screen.',
      side: 'bottom',
    },
    {
      route: '/devices',
      selector: '[data-tour="devices-adopt"]',
      title: 'Adopt a device',
      description: 'Click "Adopt Device" to pair new hardware — it needs an adoption token generated by that device itself.',
      side: 'bottom',
      advanceOnClick: true,
    },
    {
      selector: '[data-tour="devices-adopt-name-field"]',
      title: 'Name it',
      description: 'A display name to recognize this device by later.',
      side: 'bottom',
    },
    {
      selector: '[data-tour="devices-adopt-qr"]',
      title: 'Adoption token',
      description:
        'Scan the QR code the device itself displays, or paste its adoption token manually — either way, the token proves it\'s really that physical device.',
      side: 'bottom',
    },
    {
      selector: '[data-tour="devices-adopt-cancel"]',
      title: 'Adopt',
      description: 'Optionally pick a screen to assign it to right away, then Adopt — you can also assign it later from the device list.',
      side: 'top',
    },
    {
      route: '/devices',
      selector: '[data-tour="devices-table"]',
      title: 'Your devices',
      description: 'Every adopted device shows up here, with its online status and which screen (if any) it\'s assigned to.',
      side: 'top',
      before: closeAdoptDialogIfStillOpen,
    },
    {
      selector: '[data-tour="devices-filter"]',
      title: 'Finding a device',
      description: 'Once you have more than a handful, filter the list by name here.',
      side: 'bottom',
    },
    {
      selector: '[data-tour="devices-key-column"]',
      title: 'Device key',
      description:
        'The key button copies the raw device key; the share button copies a one-time dynamic URL with the key embedded instead — safe to hand to someone else, since it\'s never written to that device\'s own storage.',
      side: 'top',
    },
    {
      selector: '[data-tour="devices-row-rename"]',
      title: 'Rename',
      description: 'Change this device\'s display name.',
      side: 'top',
    },
    {
      selector: '[data-tour="devices-row-assign"]',
      title: 'Assign to Screen',
      description: 'Attach (or re-attach) this device to a different screen — pick one, then Save.',
      side: 'top',
      advanceOnClick: true,
    },
    {
      route: '/devices',
      selector: '[data-tour="devices-row-locate"]',
      title: 'Locate Device',
      description: 'Flashes an on-screen marker on the physical device so you can find it in a room full of screens — only available while it\'s online.',
      side: 'top',
      before: closeAssignDialogIfStillOpen,
    },
    {
      route: '/matrix',
      selector: '[data-tour="matrix-page"]',
      title: 'Matrix',
      description:
        'A faster way to assign many screens to many groups at once — the same membership the Screen Groups page manages one group at a time.',
      side: 'bottom',
    },
    {
      selector: '[data-tour="matrix-checkbox-cell"]',
      title: 'Toggle membership',
      description: 'Click any cell to add or remove that screen from that group — it saves immediately, no confirmation.',
      side: 'top',
    },
  ],
}
